### ISSUE TITLE
ModuleNotFoundError: No module named 'rembg'

### ISSUE THREAD

**Issue by TheSystemGuy1337** [Haidra-Org/AI-Horde-Worker#251]
We're gonna need a bigger debugger. I'm new to the whole AI Horde thing, and as such I'm not qualified for it. I read the instructions and installed the software and went to use horde-alchemist-bridge (as I had an AMD GPU, which is impossible to use, but I had a decent Ryzen processor which enables me to donate CPU cycles to the Horde). When I configured the Horde worker (my system) and went to start the diesel engine (horde-alchemist-bridge), it crashed with this:
xformers version: 0.0.20
Could not pick default device.
Using xformers cross attention
xformers version: 0.0.20
Could not pick default device.
Traceback (most recent call last):
  File "/home/thesystemguy/AI-Horde-Worker/bridge_alchemy.py", line 15, in <module>
    from worker.workers.interrogation import InterrogationWorker
  File "/home/thesystemguy/AI-Horde-Worker/worker/workers/interrogation.py", line 2, in <module>
    from worker.jobs.interrogation import InterrogationHordeJob
  File "/home/thesystemguy/AI-Horde-Worker/worker/jobs/interrogation.py", line 15, in <module>
    from worker.post_process import post_process
  File "/home/thesystemguy/AI-Horde-Worker/worker/post_process.py", line 2, in <module>
    import rembg
ModuleNotFoundError: No module named 'rembg'

I tried running pip install -r requirements.txt to sort out any failed installs from the bootstrap rutine (when you first start the Horde configurator), but it still tossed ModuleNotFoundError: No module named 'rembg'.

**Am I an idiot, and fucked something up, or is this a n00bs mistake?**

**Comment by TheSystemGuy1337** [comment]
RELALATION: Managed to fix my fuck up, but now it just hangs on Could not pick default device. How do I specify CPU only?

**Comment by TheSystemGuy1337** [comment]
Found out it was trying to init. Case closed, I'm a moron.
