### ISSUE TITLE
ControlNet causing worker to be put into maintenance?

### ISSUE THREAD

**Issue by AlRlC** [Haidra-Org/AI-Horde-Worker#73]
In my trace.log, I've seen it affect the following:
Models: Anything, Anything v3, Openniji, Poison, Counterfeit
CN: canny, fakescribbles

```
ERROR      | 2023-03-04 02:01:22.165279 | worker.jobs.stable_diffusion:start_job:329 - Something went wrong when processing request. Please check your trace.log file for the full stack trace. Payload: {'prompt': 'Cute girl, blue hair.', 'height': 1024, 'width': 640, 'seed': '808565739', 'tiling': False, 'n_iter': 1, 'batch_size': 1, 'save_individual_images': False, 'save_grid': False, 'ddim_steps': 30, 'sampler_name': 'k_euler_a_karras', 'cfg_scale': 7.5, 'control_type': 'fakescribbles', 'init_as_control': True, 'init_img': <PIL.Image.Image image mode=RGB size=683x1024 at 0x20D6C9CDC30>, 'request_type': 'img2img', 'model': 'Counterfeit'}
TRACE      | 2023-03-04 02:01:22.169280 | worker.jobs.stable_diffusion:start_job:335 - Traceback (most recent call last):
  File "C:\Users\Airic\AI-Horde-Worker\worker\jobs\stable_diffusion.py", line 323, in start_job
    generator.generate(**gen_payload)
  File "C:\Users\Airic\AI-Horde-Worker\conda\envs\windows\lib\site-packages\nataili\util\cast.py", line 29, in wrap
    return amp.autocast(device_type="cuda", dtype=dtype)(no_grad()(func))(*args, **kwargs)
  File "C:\Users\Airic\AI-Horde-Worker\conda\envs\windows\lib\site-packages\torch\amp\autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "C:\Users\Airic\AI-Horde-Worker\conda\envs\windows\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Airic\AI-Horde-Worker\conda\envs\windows\lib\site-packages\nataili\stable_diffusion\compvis.py", line 851, in generate
    samples_ddim, _ = sampler.sample(
  File "C:\Users\Airic\AI-Horde-Worker\conda\envs\windows\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Airic\AI-Horde-Worker\conda\envs\windows\lib\site-packages\ldm\models\diffusion\ddim.py", line 105, in sample
    samples, intermediates = self.ddim_sampling(conditioning, size,
  File "C:\Users\Airic\AI-Horde-Worker\conda\envs\windows\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Airic\AI-Horde-Worker\conda\envs\windows\lib\site-packages\ldm\models\diffusion\ddim.py", line 165, in ddim_sampling
    outs = self.p_sample_ddim(img, cond, ts, index=index, use_original_steps=ddim_use_original_steps,
  File "C:\Users\Airic\AI-Horde-Worker\conda\envs\windows\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Airic\AI-Horde-Worker\conda\envs\windows\lib\site-packages\ldm\models\diffusion\ddim.py", line 213, in p_sample_ddim
    model_uncond, model_t = self.model.apply_model(x_in, t_in, c_in).chunk(2)
  File "C:\Users\Airic\AI-Horde-Worker\conda\envs\windows\lib\site-packages\cldm\cldm.py", line 333, in apply_model
    control = self.control_model(x=x_noisy, hint=cond_hint, timesteps=t, context=cond_txt)
  File "C:\Users\Airic\AI-Horde-Worker\conda\envs\windows\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Airic\AI-Horde-Worker\conda\envs\windows\lib\site-packages\cldm\cldm.py", line 295, in forward
    h += guided_hint
RuntimeError: The size of tensor a (85) must match the size of tensor b (86) at non-singleton dimension 3
```

**Comment by jug-dev** [comment]
This wasn't happening before the change that added control images to controlNet.

Every stack trace I've seen this error on has had "'init_as_control': True"

**Comment by db0** [comment]
I have disabled image_is_control now.

**Comment by jug-dev** [comment]
Rendered obsolete by hordelib.
